package main.euler

import org.scalatest.FlatSpec
import util.control.Breaks._


/**
 * Created by cevaris on 2/6/14.
 *
 * https://projecteuler.net/problem=2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
class Prob2 extends FlatSpec with Problems {


  def execute() {


//    var prev = 0 : Long
//    var curr = 1 : Long
//    val evenFibs = List[Integer]()
//    var sum = 0  : Long
//    val max = (4000000)
//
//    breakable {
//      for(i <- 0 to Integer.MAX_VALUE-1 ){
//        val next = prev + curr
//        prev = curr
//        curr = next
//
//        if(next > max) break;
//
//        if(next % 2 == 0) sum += next
//      }
//    }
//    printf(s"Sum: $sum")



//    var fibs = List[Integer](1,0)
//    var curr = 0
//    do { curr = fibs(0)+fibs(1) } while ( {fibs ::= curr; curr }  < 4000000 )
//    val sum = fibs.filter(_ % 2 == 0).foldLeft(0)(_ + _)
//    printf(s"Sum: $sum")


      var prev = 0 : Long
      var curr = 1 : Long
      var next = 1 : Long
      var sum = 0  : Long

      do {
        next = prev + curr
        prev = curr; curr = next
        if(next % 2 == 0) sum += next
      } while(curr < 4000000)

      printf(s"Sum: $sum")


  }


  it should "execute" in {
    new Prob2().execute()
  }

}
